FROM mcr.microsoft.com/windows/servercore:ltsc2019

LABEL org.opencontainers.image.source=https://github.com/bayrakmustafa/ci-images

ENV USERNAME=""
ENV PASSWORD=""
ENV CREDENTIAL_ID=""
ENV TOTP_SECRET=""
ENV CODE_SIGN_TOOL_PATH=C:\CodeSignTool
ENV ENVIRONMENT_NAME=PROD
ENV JAVA_VERSION jdk-11.0.20.1+1

# $ProgressPreference: https://github.com/PowerShell/PowerShell/issues/2138#issuecomment-251261324
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Write-Host ('Downloading https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi ...'); \
    curl.exe -LfsSo openjdk.msi https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi ; \
    Write-Host ('Verifying sha256 (51785957427c5f34581930fbb224a44550f70d1c5ecb6f05ab27432e6a1f9a75) ...'); \
    if ((Get-FileHash openjdk.msi -Algorithm sha256).Hash -ne '51785957427c5f34581930fbb224a44550f70d1c5ecb6f05ab27432e6a1f9a75') { \
        Write-Host 'FAILED!'; \
        exit 1; \
    }; \
    \
    New-Item -ItemType Directory -Path C:\temp | Out-Null; \
    \
    Write-Host 'Installing using MSI ...'; \
    $proc = Start-Process -FilePath "msiexec.exe" -ArgumentList '/i', 'openjdk.msi', '/L*V', 'C:\temp\OpenJDK.log', \
    '/quiet', 'ADDLOCAL=FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome', 'INSTALLDIR=C:\openjdk-11' -Wait -Passthru; \
    $proc.WaitForExit() ; \
    if ($proc.ExitCode -ne 0) { \
        Write-Host 'FAILED installing MSI!' ; \
        exit 1; \
    }; \
    \
    Remove-Item -Path C:\temp -Recurse | Out-Null; \
    Write-Host 'Removing openjdk.msi ...'; \
    Remove-Item openjdk.msi -Force

RUN Write-Host 'Verifying install ...'; \
    Write-Host 'javac --version'; javac --version; \
    Write-Host 'java --version'; java --version; \
    \
    Write-Host 'Complete.'

CMD ["jshell"]

# Add CodeSignTool
RUN New-Item -ItemType Directory -Force -Path C:\Setup
RUN Invoke-WebRequest -OutFile C:\Setup\CodeSignTool-v1.2.7.zip "https://www.ssl.com/download/codesigntool-for-windows"

RUN Expand-Archive -LiteralPath C:\Setup\CodeSignTool-v1.2.7.zip -DestinationPath C:/ -Force
RUN Move-Item -Destination "C:\CodeSignTool" -Path "C:\CodeSignTool-v1.2.7-windows"
RUN New-Item -ItemType Directory -Force -Path C:\CodeSignTool

COPY ./codesign-tool C:/CodeSignTool
COPY ./entrypoint.ps1 C:/CodeSignTool/entrypoint.ps1
COPY ./examples C:/CodeSignTool/Examples

RUN New-Item -ItemType Directory -Force -Path C:\CodeSignTool\output

WORKDIR C:/CodeSignTool

ENTRYPOINT ["powershell", "C:\\CodeSignTool\\entrypoint.ps1"]
